Repository World-of-ML/Play-With-Python, pull requests merged in 2022-12, with the labels that each got.

#55 HANGMAN GAME
  Hangman/README.md
  Hangman/hangman.py
  Hangman/images/Screenshot 2022-12-05 at 7.05.22 PM.png
  Hangman/images/Screenshot 2022-12-05 at 7.11.06 PM.png
  Hangman/images/Screenshot 2022-12-05 at 7.11.24 PM.png
  Hangman/images/Screenshot 2022-12-05 at 7.11.43 PM.png
  Hangman/images/Screenshot 2022-12-05 at 7.12.43 PM.png
  Hangman/words.txt
Labels: Approved, CODEPEAK 2022, Medium

#57 Maze Game
  MazeGame/README.md
  MazeGame/__pycache__/disjointSet.cpython-310.pyc
  MazeGame/__pycache__/disjointSet.cpython-39.pyc
  MazeGame/__pycache__/maze.cpython-39.pyc
  MazeGame/disjointSet.py
  MazeGame/maze.py
  MazeGame/mazes/10by10_maze.txt
  MazeGame/mazes/10by10_portals.txt
  MazeGame/mazes/5by5_maze.txt
  MazeGame/mazes/5by5_portals.txt
  MazeGame/pymaze.py
  MazeGame/res/demo_block.png
  MazeGame/res/demo_game.gif
  MazeGame/res/demo_solve.gif
Labels: Approved, CODEPEAK 2022, Medium

#67 Pong Game
  Pong Game/Images/Screenshot 2022-12-08 at 7.51.46 AM.png
  Pong Game/Images/Screenshot 2022-12-08 at 7.56.42 AM.png
  Pong Game/README.md
  Pong Game/pong.py
Labels: Approved, points:10, CodePeak 22

#71 Tetris Game
  Tetris/Images/Capture1.PNG
  Tetris/Images/Screenshot 2022-12-08 201836.jpg
  Tetris/Images/Screenshot 2022-12-09 090423.jpg
  Tetris/README.md
  Tetris/main.py
  Tetris/requirements.txt
Labels: Approved, points:10, CodePeak 22

#90 Pull Request for #28 Fidget Spinner
  Fidget Game/Images/Screenshot 2022-12-09 225435.jpg
  Fidget Game/Images/Screenshot 2022-12-09 225511.jpg
  Fidget Game/README.md
  Fidget Game/fidget.py
  Fidget Game/requirements.txt
Labels: Approved, points:10, CodePeak 22

#114 Created Simon Says game
  Simon Says/Images/Python Turtle Graphics 10-12-2022 00_18_49.png
  Simon Says/Images/demonstration.mp4
  Simon Says/README.md
  Simon Says/simonsays.py
Labels: Approved, points:10, CodePeak 22

#89 Created Connect 4 Game
  Connect 4 Game/README.md
  Connect 4 Game/connect4.py
  Connect 4 Game/images/image.jpg
  Connect 4 Game/images/image2.jpg
  Connect 4 Game/images/image3.jpg
  Connect 4 Game/images/image4.jpg
Labels: Approved, points:10, CodePeak 22

#116 Pull Request for #98 Random Quote Generator
  Quote Generator/Images/Screenshot 2022-12-10 104047.jpg
  Quote Generator/Images/Screenshot 2022-12-10 104128.jpg
  Quote Generator/Images/Screenshot 2022-12-10 104247.jpg
  Quote Generator/README.md
  Quote Generator/main.py
  Quote Generator/requirements.txt
Labels: Approved, points:10, CodePeak 22

#118 Guess the Number Game
  Guess the Number Game/Images/Image1.png
  Guess the Number Game/Images/image2.png
  Guess the Number Game/README.md
  Guess the Number Game/guess_number.py
Labels: Approved, points:10, CodePeak 22

#120 Wikipedia Clone
  Wikipedia Clone/Images/Wikipedia Clone - Google Chrome 11-12-2022 18_18_50.png
  Wikipedia Clone/README.md
  Wikipedia Clone/WikiClone/WikiClone/__init__.py
  Wikipedia Clone/WikiClone/WikiClone/__pycache__/__init__.cpython-310.pyc
  Wikipedia Clone/WikiClone/WikiClone/__pycache__/settings.cpython-310.pyc
  Wikipedia Clone/WikiClone/WikiClone/__pycache__/urls.cpython-310.pyc
  Wikipedia Clone/WikiClone/WikiClone/__pycache__/wsgi.cpython-310.pyc
  Wikipedia Clone/WikiClone/WikiClone/asgi.py
  Wikipedia Clone/WikiClone/WikiClone/settings.py
  Wikipedia Clone/WikiClone/WikiClone/urls.py
  Wikipedia Clone/WikiClone/WikiClone/wsgi.py
  Wikipedia Clone/WikiClone/main/__init__.py
  Wikipedia Clone/WikiClone/main/__pycache__/__init__.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/__pycache__/admin.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/__pycache__/apps.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/__pycache__/models.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/__pycache__/urls.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/__pycache__/views.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/admin.py
  Wikipedia Clone/WikiClone/main/apps.py
  Wikipedia Clone/WikiClone/main/migrations/__init__.py
  Wikipedia Clone/WikiClone/main/migrations/__pycache__/__init__.cpython-310.pyc
  Wikipedia Clone/WikiClone/main/models.py
  Wikipedia Clone/WikiClone/main/templates/main/index.html
  Wikipedia Clone/WikiClone/main/tests.py
  Wikipedia Clone/WikiClone/main/urls.py
  Wikipedia Clone/WikiClone/main/views.py
  Wikipedia Clone/WikiClone/manage.py
  Wikipedia Clone/WikiClone/pyvenv.cfg
Labels: Approved, CodePeak 22, points:35

#119 #104 Calculator App
  Calculator/Images/Screenshot 2022-12-10 202911.jpg
  Calculator/Images/Screenshot 2022-12-10 203649.jpg
  Calculator/Images/Screenshot 2022-12-10 203719.jpg
  Calculator/README.md
  Calculator/calc.py
Labels: Approved, points:10, CodePeak 22

#123 TODO App #111
  TODO App/images/2022-12-17 (1).png
  TODO App/images/todo ui.png
  TODO App/main.py
  TODO App/readme.md
  TODO App/requirements.txt
Labels: Approved, CodePeak 22, points:5

#124 Image Grayscalling
  Image Grayscalling/Images/Image2.jpg
  Image Grayscalling/Images/Image3.jpg
  Image Grayscalling/Images/Image4.jpg
  Image Grayscalling/Images/Image5.jpg
  Image Grayscalling/Images/Image6.png
  Image Grayscalling/Images/image1.jpg
  Image Grayscalling/README.md
  Image Grayscalling/image_grayscale.py
Labels: Approved, points:10, CodePeak 22

#125 Created IMG to PDF converter using Tkinter and Python
  Img To PDF/Images/cmdexample.jpeg
  Img To PDF/Images/file 0.pdf
  Img To PDF/Images/tk 18-12-2022 17_38_46.png
  Img To PDF/README.md
  Img To PDF/imgtopdf.py
Labels: Changes Requested

#126 Pull request for Issue #122 Pomodoro App
  Pomodoro App/Images/Screenshot 2022-12-17 204728.jpg
  Pomodoro App/Images/pomodoro.gif
  Pomodoro App/README.md
  Pomodoro App/index.py
  Pomodoro App/resources/tomato.png
Labels: Approved, points:10, CodePeak 22

#115 Dice with Death Game Issue#34
  Dice with Death/Images/computer_wins_case.png
  Dice with Death/Images/first_screen.png
  Dice with Death/Images/home_screen.png
  Dice with Death/Images/player_wins_case.png
  Dice with Death/Images/playing_area.png
  Dice with Death/Images/tie_case.png
  Dice with Death/README.md
  Dice with Death/main.pyw
Labels: Changes Requested

#127 PDF to Text Converter
  PDF to Text Converter/Images/2022-12-20.png
  PDF to Text Converter/Images/pdf to text 1.png
  PDF to Text Converter/Images/pdf to text2.png
  PDF to Text Converter/Images/pdf to text3.png
  PDF to Text Converter/main.py
  PDF to Text Converter/readme.md
  PDF to Text Converter/requirements.txt
Labels: Approved, points:10, CodePeak 22

#128 Hacking Mini Game
  Hacking Mini Game/Images/img1.png
  Hacking Mini Game/Images/img2.png
  Hacking Mini Game/README.md
  Hacking Mini Game/hackingMiniGame.py
Labels: Approved, points:10, CodePeak 22

#121 Digital Clock
  Digital clock/Images/Image1.png
  Digital clock/Images/Image2.png
  Digital clock/main.py
  Digital clock/readme.md
  Digital clock/requirements.txt
Labels: Approved, CodePeak 22, points:5

#132 Weight Converter
  Weight Converter/images/weight converter1.png
  Weight Converter/images/weight converter2.png
  Weight Converter/main.py
  Weight Converter/readme.md
  Weight Converter/requirements.txt
Labels: Approved, points:10, CodePeak 22

#130 Age Calculator #91
  Age Calculator/Images/Image1.jpg
  Age Calculator/Images/Image2.jpg
  Age Calculator/Images/Image3.jpg
  Age Calculator/README.md
  Age Calculator/age_cal_prac.py
  Age Calculator/requirements.txt
Labels: Approved, CodePeak 22, points:5

#131 Created Currency Converter
  Currency Converter/Images/Input.png
  Currency Converter/Images/Output.png
  Currency Converter/README.md
  Currency Converter/currencyconverter.py
Labels: Approved, points:10, CodePeak 22

#133 Add files of automatic email sender
  Automatic Email Sender/Images/image-1.png
  Automatic Email Sender/main.py
  Automatic Email Sender/readme.md
  Automatic Email Sender/requirements.txt
Labels: Approved, points:10, CodePeak 22

#134 Quiz Game
  Quiz Game/README.md
  Quiz Game/__pycache__/data.cpython-311.pyc
  Quiz Game/__pycache__/question_model.cpython-311.pyc
  Quiz Game/__pycache__/quiz_brain.cpython-311.pyc
  Quiz Game/__pycache__/ui.cpython-311.pyc
  Quiz Game/data.py
  Quiz Game/images/Screenshot 2022-12-24 202043.jpg
  Quiz Game/images/Screenshot 2022-12-24 202126.jpg
  Quiz Game/images/Screenshot 2022-12-24 202149.jpg
  Quiz Game/images/quizzler.gif
  Quiz Game/main.py
  Quiz Game/question_model.py
  Quiz Game/quiz_brain.py
  Quiz Game/resources/false.png
  Quiz Game/resources/true.png
  Quiz Game/ui.py
Labels: Approved, points:10, CodePeak 22

#135 PDF Merger App
  PDF Merger App/images/merged.png
  PDF Merger App/images/pdf1.png
  PDF Merger App/images/pdf2.png
  PDF Merger App/images/pic 1.png
  PDF Merger App/images/pic 2.png
  PDF Merger App/images/pic 3.png
  PDF Merger App/images/pic 4.png
  PDF Merger App/images/pic 5.png
  PDF Merger App/main.py
  PDF Merger App/readme.md
  PDF Merger App/requirements.txt
Labels: Approved, points:10, CodePeak 22

#129 PDF Downloader App
  Pdf Downloader/README.md
  Pdf Downloader/image/Output.png
  Pdf Downloader/image/img-01.png
  Pdf Downloader/image/img-02.png
  Pdf Downloader/image/logo.png
  Pdf Downloader/pdf_downloader.py
  Pdf Downloader/requirements.txt
Labels: Changes Requested

#136 Speech to Text App
  Speech to Text App/images/readme.txt
  Speech to Text App/images/speech to text 1.png
  Speech to Text App/images/speech to text 2.png
  Speech to Text App/main.py
  Speech to Text App/readme.md
  Speech to Text App/requirements.txt
Labels: Approved, points:10, CodePeak 22

#137 Text Extractor #107
  Text Extractor/images/pic1.png
  Text Extractor/images/pic2.png
  Text Extractor/images/pic3.png
  Text Extractor/main.py
  Text Extractor/readme.md
  Text Extractor/requirements.txt
Labels: Approved, points:10, CodePeak 22

#139 QR Code Generator #96
  QR Code Generator/Images/Image-1.png
  QR Code Generator/main.py
  QR Code Generator/readme.md
  QR Code Generator/requirements.txt
Labels: Approved, points:10, CodePeak 22

#140 Random Name Generator #97
  Random Name Generator/images/female name.png
  Random Name Generator/images/male name.png
  Random Name Generator/images/name gui.png
  Random Name Generator/images/readme.txt
  Random Name Generator/main.py
  Random Name Generator/readme.md
  Random Name Generator/requirements.txt
Labels: Approved, CodePeak 22, points:5

#141 Pull Request for #138 Turtle Game
  Turtle Crossing Game/Images/Screenshot 2022-12-26 142605.jpg
  Turtle Crossing Game/Images/Screenshot 2022-12-26 142626.jpg
  Turtle Crossing Game/Images/Screenshot 2022-12-26 142656.jpg
  Turtle Crossing Game/README.md
  Turtle Crossing Game/__pycache__/car_manager.cpython-311.pyc
  Turtle Crossing Game/__pycache__/player.cpython-311.pyc
  Turtle Crossing Game/__pycache__/scoreboard.cpython-311.pyc
  Turtle Crossing Game/car_manager.py
  Turtle Crossing Game/main.py
  Turtle Crossing Game/player.py
  Turtle Crossing Game/requirements.txt
  Turtle Crossing Game/scoreboard.py
  Turtle Crossing Game/turtle_crossing.gif
Labels: Approved, points:25, CodePeak 22

#142 Stopwatch #93
  Stopwatch/images/stopwatch1.png
  Stopwatch/images/stopwatch2.png
  Stopwatch/main.py
  Stopwatch/readme.md
  Stopwatch/requirements.txt
Labels: Approved, CodePeak 22, points:5

#143 Morse Code Converter
  Morse Code Converter/README.md
  Morse Code Converter/images/Screenshot 2022-12-31 at 12.25.44 PM.png
  Morse Code Converter/images/Screenshot 2022-12-31 at 12.26.35 PM.png
  Morse Code Converter/main.py
  Morse Code Converter/morse.py
  Morse Code Converter/morse2text.json
  Morse Code Converter/text2morse.json
Labels: Approved, points:10, CodePeak 22

#144 Image Compression App
  Image Compressor App/images/Compressed_parrot.jpeg
  Image Compressor App/images/parrot.jpeg
  Image Compressor App/main.py
  Image Compressor App/readme.md
  Image Compressor App/requirements.txt
Labels: Approved, points:10, CodePeak 22
