Repository World-of-ML/Play-With-Python, pull requests merged in 2023-01, with the labels that each got.

#145 Watermark Generator
  Image Watermark Generator/README.md
  Image Watermark Generator/images/cmd.png
  Image Watermark Generator/images/generatedImage.png
  Image Watermark Generator/images/gui.png
  Image Watermark Generator/images/res.png
  Image Watermark Generator/images/selectedImage.png
  Image Watermark Generator/lion.jpg
  Image Watermark Generator/lion_watermarked.jpg
  Image Watermark Generator/result/watermark.jpg
  Image Watermark Generator/watermarkGenerator.py
  Image Watermark Generator/watermarkGeneratorGUI.py
Labels: Approved, points:10, CodePeak 22

#146 Random Password Generator
  Password Generator/README.md
  Password Generator/images/cmd.png
  Password Generator/images/gui.png
  Password Generator/images/gui2.png
  Password Generator/passwordGenerator.py
  Password Generator/passwordGeneratorGUI.py
Labels: Approved, CodePeak 22, points:5

#147 YouTube Video Downloader
  Image Watermark Generator/README.md
  YouTube Video Downloader/README.md
  YouTube Video Downloader/images/app.png
  YouTube Video Downloader/images/detailsFilled.png
  YouTube Video Downloader/images/downloadSuccess.png
  YouTube Video Downloader/images/lionRoarVideo.png
  YouTube Video Downloader/youtubeDownloaderGUI.py
Labels: Approved, points:10, CodePeak 22

#148 CSV to JSON Converter
  CSV to JSON Converter/images/gui1.png
  CSV to JSON Converter/images/gui2.png
  CSV to JSON Converter/images/sample csv file.png
  CSV to JSON Converter/images/sample json output.png
  CSV to JSON Converter/main.py
  CSV to JSON Converter/readme.md
  CSV to JSON Converter/requirements.txt
Labels: Approved, CodePeak 22, points:5

#149 Alarm Clock
  Alarm Clock/Readme.md
  Alarm Clock/alarm.mp3
  Alarm Clock/alarm.py
  Alarm Clock/images/img-1.png
  Alarm Clock/requirements.txt
Labels: Approved, CodePeak 22, points:5

#151 Google Search Automation
  Google Search Automation/images/search gui.png
  Google Search Automation/main.py
  Google Search Automation/readme.md
  Google Search Automation/requirements.txt
Labels: Approved, CodePeak 22, points:5

#150 URL Shortener
  Password Generator/README.md
  URL Shortener/README.md
  URL Shortener/images/gui.png
  URL Shortener/images/gui2.png
  URL Shortener/requirements.txt
  URL Shortener/urlShortenerGUI.py
Labels: Approved, CodePeak 22, points:5

#154 Weather App
  Weather App/images/clear sky.png
  Weather App/images/haze.png
  Weather App/images/heavy rain.png
  Weather App/images/partly cloudy.png
  Weather App/images/scattered clouds.png
  Weather App/images/windy.png
  Weather App/main.py
  Weather App/readme.md
  Weather App/requirements.txt
Labels: Approved, points:10, CodePeak 22

#152 Spelling Corrector App
  Spelling Corrector App/README.md
  Spelling Corrector App/images/app.png
  Spelling Corrector App/images/app_correct.png
  Spelling Corrector App/images/app_no_input.png
  Spelling Corrector App/images/app_start.png
  Spelling Corrector App/requirements.txt
  Spelling Corrector App/spellingCorrector.py
Labels: Approved, points:10, CodePeak 22

#155 Audio book
  Audio Book/Images/gui.png
  Audio Book/README.md
  Audio Book/main.py
  Audio Book/requirments.txt
Labels: Approved, points:10, CodePeak 22

#158 Haunted House Game
  Haunted House/Image/img.png
  Haunted House/Readme.md
  Haunted House/haunted_house.py
  Haunted House/requirements.txt
Labels: Approved, CodePeak 22, points:5

#175 screen Recorder app
  Screen Recorder/Images/image1.jpeg
  Screen Recorder/main.py
  Screen Recorder/readme.md
  Screen Recorder/requirements.txt
Labels: Approved, CodePeak 22, points:5

#177 Music Player App
  Music Player App/Music Player App.py
  Music Player App/README.md
  Music Player App/image/Screenshot 2023-01-06 at 5.56.02 PM.png
Labels: Approved, CodePeak 22, points:20

#178 Added a New Python Script
  news_app/images/image1.png
  news_app/images/image2.png
  news_app/news_app.py
  news_app/readme.md
  news_app/requirements.txt
Labels: Approved, DWOC 2023
